server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/odfp-db
    username: postgres
    password: root-password-123
    hikari:
      schema: auth-service-db

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: auth-service-db
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: auth-service-db
    enabled: true

  kafka:
    producers:
      registration:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        acks: all
        enable-idempotence: true
        retries: 3
        max-in-flight-requests-per-connection: 5
        batch-size: 16384
        linger-ms: 0
        buffer-memory: 33554432
        delivery-timeout-ms: 5000
        request-timeout-ms: 3000
        max-block-ms: 3000
    bootstrap-servers: localhost:9092

topic:
  user-registration: user-registration-topic

jwt:
  secret-key: co7IB8BVZ2ZCWoyjnKbrX4ByykVOvY38vtv2DNK9kN4=
  expire-time-access-token: 900000
  expire-time-refresh-token: 3
scheduling:
  fixed-rate: 900000